Strip trailing stuff before comparing to MIN_REQUIRED_VERSION
Was seeeing:
wled.exceptions.WLEDUnsupportedVersionError: Unsupported firmware version 0.14.0-b1. Minimum required version is 0.14.0. Please update your WLED device.